on:
  push:
    branches: [master]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    outputs:
      hello: ${{ steps.check-hello.outputs.modified }}
      hello2: ${{ steps.check-hello2.outputs.modified }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: check-hello
        name: Check whether hello has changed
        shell: pwsh
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match 'src/first' }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=modified::$HasDiff"

      - id: check-hello2
        name: Check whether hello2 has changed
        shell: pwsh
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match 'src/second' }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=modified::$HasDiff"

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: check-diff

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_JSON }}

    - id: deploy
      if: ${{ needs.check-diff.outputs.hello == 'True' }}
      name: Deploy to Google Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v0
      with:
        name: hello-github-cicd
        runtime: nodejs16
        entry_point: main
        region: asia-east1
        source_dir: src/first
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        description: "GitHub Action CI/CD test"

    - id: deploy2
      if: ${{ needs.check-diff.outputs.hello2 == 'True' }}
      name: Deploy second to Google Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v0
      with:
        name: hello-github-cicd-2
        runtime: nodejs16
        entry_point: main
        region: asia-east1
        source_dir: src/second
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        description: "GitHub Action CI/CD test 2"
