on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_JSON }}

    - id: deploy
      name: Deploy to Google Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v0
      with:
        name: hello-github-cicd
        runtime: nodejs16
        entry_point: main
        region: asia-east1
        source_dir: src/
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        description: "GitHub Action CI/CD test"

    - id: test
      name: Deployment Test
      run: 'curl "${{ steps.deploy.outputs.url }}"'